services:
  delineator:
    build: .
    volumes:
      - ./in:/in
      - ./data:/data
      - ./out:/out
#      - ./src:/src
    command: echo "run as docker compose run --rm delineator python run.py"

  nitrate:
    build: .
    volumes:
      - ./example/nitrate/in:/in
      - ./data:/data
      - ./example/nitrate/out:/out
    command: echo "run as docker compose run --rm nitrate python run.py"